### ISSUE TITLE
TODO: React components and layout using mock data

### ISSUE THREAD

**Issue by kaseyjcowley** [kchunterdeluxe/AutioFrontend#1]
- [x] Layout main GarageList / other components
- [x] Make GarageList functional with mock data
- [x] Possibly figure out app routing
- [x] Modify app routing to include showing individual vehicles
- [x] Search capabilities to filter the list of vehicles in the GarageList
- [x] Make GarageList functional with actual server data

**Comment by kaseyjcowley** [comment]
All finished! v0.1.0 released.
